name: Run Tests on PR

on:
  pull_request:
    branches:
      - master

jobs:
  tests:
    name: Install dependancies and run tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Get Composer Cache Directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache Composer Dependancies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer

      - name: Setup PHP Environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.3'

      - name: Install Composer Dependancies
        run: composer install

      - name: Generate encryption key
        run: php artisan key:generate

      - name: Run PHPUnit Tests
        run: ./vendor/bin/phpunit
